spring:
  rabbitmq:
    queue: usadosbr.leads.forms
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: "mongodb://root:root@localhost:27017/admin"

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

logging:
  level:
    root: info
    com:
      usadosbr: TRACE
